TXREADS = 'txReads'
TXRPKM = 'txRPKM'
CDREADS = 'cdReads'
CDRPKM = 'cdRPKM'

TXREADS_LIST = ['txReads0','txReads1','txReads2']
TXRPKM_LIST = ['txRPKM0','txRPKM1','txRPKM2']
CDREADS_LIST = ['cdReads0','cdReads1','cdReads2']
CDRPKM_LIST = ['cdRPKM0','cdRPKM1','cdRPKM2']

PLOT = [TXREADS,TXRPKM,CDREADS,CDRPKM]
PLOT_LIST = [TXREADS_LIST,TXRPKM_LIST,CDREADS_LIST,CDRPKM_LIST]
